In [1]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import regularizers
import xgboost as xgb
from sklearn.decomposition import PCA
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import RobustScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
pd.set_option('display.max_columns',None)
warnings.filterwarnings('ignore')
%matplotlib inline 

In [2]:
xbalanced_file_path = '/Users/jayeshbangar/Desktop/IDS_project/x_balanced.npy'

# Load the NumPy array from the file
xbalanced = np.load(xbalanced_file_path)
ybalanced_file_path = '/Users/jayeshbangar/Desktop/IDS_project/y_balanced.npy'
ybalanced = np.load(ybalanced_file_path, allow_pickle=True)

In [3]:
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
import seaborn as sns
import time
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score, roc_auc_score,roc_curve
x_train, x_test, y_train, y_test = train_test_split(xbalanced,ybalanced,test_size=0.2,random_state=42)

print('===========x_train=============')
print(x_train)
print(x_train.shape)
print('===========x_test=============')
print(x_test)
print(x_test.shape)
print('===========y_train=============')
print(y_train)
print(y_train.shape)
print('===========y_test=============')
print(y_test)
print(y_test.shape)

===========x_train=============
[[2.20000000e+01 1.16719309e+07 2.10000000e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [8.00000000e+01 6.30864630e+07 7.00000000e+00 ... 1.22000000e+07
  3.20000000e+07 8.01620100e+06]
 [8.00000000e+01 8.38734060e+07 6.00000000e+00 ... 0.00000000e+00
  8.37000000e+07 8.37000000e+07]
 ...
 [8.00000000e+01 2.52095494e+06 3.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [5.30000000e+01 3.12770000e+04 2.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [8.08000000e+03 6.78620000e+04 4.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
(87200, 78)
===========x_test=============
[[4.44000000e+02 1.19299495e+08 2.80466712e+03 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.15110000e+04 1.04000000e+02 1.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.10000000e+01 2.90000000e+02 2.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [8.00000000e+01 3.0035

In [4]:
labels=np.unique(y_test)
print(labels)
print(len(labels))
print('-------------------')

classes = []
for i in range(0,len(labels)):
    classes.append(i)
print(classes)
print('-------------------')

map=dict(zip(labels,classes))
print(map)
print('-------------------')


y_test_class=[]

for i in range(0, len(y_test)):
    y_test_class.append(map[y_test[i]])
    
y_test_class=np.asarray(y_test_class)

print(y_test_class)
print(len(y_test_class))

['BENIGN' 'Bot' 'DDoS' 'DoS GoldenEye' 'DoS Hulk' 'DoS Slowhttptest'
 'DoS slowloris' 'FTP-Patator' 'Heartbleed' 'Infiltration' 'PortScan'
 'SSH-Patator' 'Web Attack � Brute Force' 'Web Attack � Sql Injection'
 'Web Attack � XSS']
15
-------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
-------------------
{'BENIGN': 0, 'Bot': 1, 'DDoS': 2, 'DoS GoldenEye': 3, 'DoS Hulk': 4, 'DoS Slowhttptest': 5, 'DoS slowloris': 6, 'FTP-Patator': 7, 'Heartbleed': 8, 'Infiltration': 9, 'PortScan': 10, 'SSH-Patator': 11, 'Web Attack � Brute Force': 12, 'Web Attack � Sql Injection': 13, 'Web Attack � XSS': 14}
-------------------
[ 8 10  7 ...  6  5 11]
21800


In [5]:

labels=np.unique(y_train)
print(labels)
print(len(labels))
print('-------------------')

classes = []
for i in range(0,len(labels)):
    classes.append(i)
print(classes)
print('-------------------')

map=dict(zip(labels,classes))
print(map)
print('-------------------')


y_train_class=[]

for i in range(0, len(y_train)):
    y_train_class.append(map[y_train[i]])
    
y_train_class=np.asarray(y_train_class)

print(y_train_class)
print(len(y_train_class))

['BENIGN' 'Bot' 'DDoS' 'DoS GoldenEye' 'DoS Hulk' 'DoS Slowhttptest'
 'DoS slowloris' 'FTP-Patator' 'Heartbleed' 'Infiltration' 'PortScan'
 'SSH-Patator' 'Web Attack � Brute Force' 'Web Attack � Sql Injection'
 'Web Attack � XSS']
15
-------------------
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
-------------------
{'BENIGN': 0, 'Bot': 1, 'DDoS': 2, 'DoS GoldenEye': 3, 'DoS Hulk': 4, 'DoS Slowhttptest': 5, 'DoS slowloris': 6, 'FTP-Patator': 7, 'Heartbleed': 8, 'Infiltration': 9, 'PortScan': 10, 'SSH-Patator': 11, 'Web Attack � Brute Force': 12, 'Web Attack � Sql Injection': 13, 'Web Attack � XSS': 14}
-------------------
[11  5  4 ... 12  0  1]
87200


In [6]:
from keras.utils import to_categorical

y_train_class, y_test_class = to_categorical(y_train_class), to_categorical(y_test_class)

print(y_train_class)
print(y_train_class.shape)

print(y_test_class)
print(y_test_class.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
(87200, 15)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(21800, 15)


In [7]:
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
import seaborn as sns
import time
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score, roc_auc_score,roc_curve

In [8]:
start = time.time()
xgb = XGBClassifier(random_state=42)

xgb.fit(x_train,y_train_class)

xgbpreds = xgb.predict(x_test)

print("Time", time.time()-start)
print("Accuracy",accuracy_score(y_test_class,xgbpreds))
print(classification_report(y_test_class,xgbpreds))

Time 8.07565188407898
Accuracy 0.9839908256880734
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3056
           1       1.00      0.99      1.00       998
           2       1.00      1.00      1.00      1543
           3       1.00      1.00      1.00      2271
           4       1.00      1.00      1.00      1637
           5       1.00      0.99      1.00      2025
           6       1.00      1.00      1.00      2036
           7       1.00      1.00      1.00      2168
           8       1.00      1.00      1.00       400
           9       1.00      1.00      1.00       388
          10       1.00      1.00      1.00      1607
          11       1.00      1.00      1.00      1957
          12       0.85      0.91      0.88       982
          13       0.99      1.00      0.99       375
          14       0.71      0.54      0.61       357

   micro avg       0.99      0.99      0.99     21800
   macro avg       0.97      0